version: '3.8'

volumes:
  datafiles:

services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=user
      - MYSQL_TCP_PORT=3306
    volumes:
      - datafiles:/var/lib/mysql
      - ./db_create_script.sql:/docker-entrypoint-initdb.d/db_create_script.sql
    restart: always

  website:
    container_name: php73
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=user
      - MYSQL_DBNAME=myspotify
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - mysql

